import express from 'express';
import path from 'path';
import crypto from 'crypto';
import rateLimit from 'express-rate-limit';
import * as admin from 'firebase-admin';
import { FieldValue } from 'firebase-admin/firestore';
import { GoogleGenAI, Type } from '@google/genai';
import { createServer as createViteServer } from 'vite';
import { requireAuthenticated, requireAdmin, enforceAiBudget, sanitizeAiErrorResponse, markFinancialDataAsModelled, markAnalyticsDataAsModelled, invalidatePremiumEntitlement } from './runtime-security.ts';
import { requireFirebaseUser, verifyMercadoPagoWebhook, recordWebhookIdempotency, requireMercadoPagoCredential, enforceServerPrice, rejectSimulatedPreferenceResponse, verifyPaymentAgainstMercadoPago, rejectUnimplementedCancellation, calculateCouponPrice, resolveCanonicalBasePrice } from './mercadopago-security.ts';

if (!(admin as any).apps?.length) {
  try { (admin as any).initializeApp(); } catch (e) { console.error('Firebase Admin initialization notice:', e); }
}

const AI_PUBLIC_ATHLETE_FIELDS = [
  'name', 'avatar', 'sport', 'position', 'age', 'city', 'province', 'level',
  'preferredFootOrHand', 'bio', 'stats', 'availableForTrials', 'isVerified',
  'rating', 'verificationTier', 'activityLevel', 'trustScore'
];

function toPublicAiAthlete(id: string, data: any): any {
  const publicAthlete: any = { id };
  for (const field of AI_PUBLIC_ATHLETE_FIELDS) {
    if (data?.[field] !== undefined) publicAthlete[field] = data[field];
  }
  return publicAthlete;
}

async function getAuthoritativeAthlete(clientAthlete: any): Promise<any> {
  if (!clientAthlete || !clientAthlete.id) return null;
  const id = String(clientAthlete.id);
  try {
    const docSnap = await (admin as any).firestore().collection('publicAthletes').doc(id).get();
    if (docSnap.exists) return toPublicAiAthlete(id, docSnap.data() || {});
  } catch (e) { console.error('Error fetching public athlete projection for AI:', e); }
  return null;
}

async function getAuthoritativeCandidates(candidates: any[]): Promise<any[]> {
  if (!Array.isArray(candidates)) return [];
  const resolved = await Promise.all(candidates.map(async c => getAuthoritativeAthlete(c)));
  return resolved.filter(Boolean);
}

const app = express();
const PORT = Number(process.env.PORT) || 8080;
app.use(express.json({ limit: '2mb' }));
app.use((_req, res, next) => { res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('X-Frame-Options', 'SAMEORIGIN'); res.setHeader('X-XSS-Protection', '1; mode=block'); next(); });

const generalLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 300, standardHeaders: true, legacyHeaders: false, message: { error: 'Demasiadas solicitudes al servidor. Por favor intente más tarde.' } });
const aiLimiter = rateLimit({ windowMs: 10 * 60 * 1000, max: 40, standardHeaders: true, legacyHeaders: false, keyGenerator: (req: any) => req.user?.uid || req.ip || 'anonymous', message: { error: 'Límite de consultas de Inteligencia Artificial alcanzado (40 solicitudes cada 10 minutos). Por favor aguarde unos minutos.' } });
const paymentLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 25, standardHeaders: true, legacyHeaders: false, message: { error: 'Demasiadas solicitudes de pago o validación. Intente más tarde.' } });

app.use('/api/', generalLimiter);
app.use('/api/ai/', requireAuthenticated, aiLimiter, enforceAiBudget, sanitizeAiErrorResponse);
app.use('/api/financial/', requireAuthenticated, markFinancialDataAsModelled);
app.use('/api/financial/summary', requireAdmin);
app.use('/api/financial/reserve-config', requireAdmin);
app.use('/api/financial/executive-report', requireAdmin);
app.use('/api/admin/', requireAdmin);
app.use('/api/analytics/summary', requireAdmin, markAnalyticsDataAsModelled);
app.use('/api/mercadopago/', paymentLimiter);
app.use('/api/mercadopago/validate-coupon', requireFirebaseUser);
app.use('/api/mercadopago/create-preference', requireFirebaseUser, requireMercadoPagoCredential, enforceServerPrice, rejectSimulatedPreferenceResponse);
app.use('/api/mercadopago/webhook', verifyMercadoPagoWebhook, recordWebhookIdempotency);
app.use('/api/mercadopago/verify-payment', requireFirebaseUser, requireMercadoPagoCredential, verifyPaymentAgainstMercadoPago);
app.use('/api/mercadopago/cancel-subscription', requireFirebaseUser, rejectUnimplementedCancellation);

const aiCache = new Map<string, { timestamp: number; data: any }>();
const CACHE_TTL_MS = 15 * 60 * 1000;
function getCachedAIResponse(key: string): any | null { const cached = aiCache.get(key); if (cached && Date.now() - cached.timestamp < CACHE_TTL_MS) return cached.data; if (cached) aiCache.delete(key); return null; }
function setCachedAIResponse(key: string, data: any) { if (aiCache.size > 200) { const firstKey = aiCache.keys().next().value; if (firstKey) aiCache.delete(firstKey); } aiCache.set(key, { timestamp: Date.now(), data }); }
function generateCacheKey(endpoint: string, payload: any, userId?: string): string { return endpoint + ':' + crypto.createHash('md5').update(JSON.stringify({ cacheScope: userId || 'anonymous', payload })).digest('hex'); }

export interface BudgetConfig { monthlyBudgetUsd:number; dailyBudgetUsd:number; aiBudgetUsd:number; firestoreBudgetUsd:number; storageBudgetUsd:number; cloudRunBudgetUsd:number; freeUserDailyAiLimit:number; premiumUserDailyAiLimit:number; freeUserMonthlyAppLimit:number; }
export interface FinancialAuditLog { id:string; timestamp:string; action:string; reason:string; estimatedSavingsUsd:number; protectionLevel:string; }
export interface UserCostRecord { userId:string; userEmail:string; role:string; isPremium:boolean; aiCallsToday:number; aiCallsTotal:number; firestoreReads:number; firestoreWrites:number; estimatedCostUsd:number; revenueGeneratedArs:number; netProfitUsd:number; isDeficit:boolean; lastActive:string; }
export interface UnitEconomics { arpuUsd:number; cacUsd:number; paybackMonths:number; churnRatePct:number; ltvUsd:number; contributionMarginPct:number; ltvToCacRatio:number; isHealthy:boolean; }
export interface AnomalyItem { id:string; detectedAt:string; type:'IA_SPIKE'|'FIRESTORE_READ_SPIKE'|'STORAGE_GROWTH'|'CONVERSION_DROP'; severity:'ALTA'|'MEDIA'|'BAJA'; title:string; metricVariation:string; aiCauseExplanation:string; mitigationApplied:string; }
export interface FinancialForecast { days30:{incomeUsd:number;costsUsd:number;cashFlowUsd:number;incomeArs:number}; days90:{incomeUsd:number;costsUsd:number;cashFlowUsd:number;incomeArs:number}; days365:{incomeUsd:number;costsUsd:number;cashFlowUsd:number;incomeArs:number}; }
export interface ActionableRecommendation { id:string; category:'PRECIOS'|'IA_LIMITS'|'MARKETING'|'COST_OPTIMIZATION'; title:string; impactEstimate:string; description:string; recommendedAction:string; }
export interface BusinessHealthScore { overallScore:number; status:'EXCELENTE'|'BUENO'|'EN_RIESGO'|'CRITICO'; components:{security:number;availability:number;profitability:number;growth:number;costControl:number;userSatisfaction:number;performance:number}; summaryText:string; }

const unitEconomicsData:UnitEconomics={arpuUsd:2.34,cacUsd:12.5,paybackMonths:5.5,churnRatePct:2.1,ltvUsd:108.08,contributionMarginPct:97.3,ltvToCacRatio:8.6,isHealthy:true};
const anomalyDetections:AnomalyItem[]=[
{id:'anom_01',detectedAt:new Date(Date.now()-3600000*2).toISOString(),type:'IA_SPIKE',severity:'MEDIA',title:'Pico Inesperado de Consultas en Scout IA (+145%)',metricVariation:'+145% llamadas a Gemini Flash en 2h',aiCauseExplanation:'Varias agencias realizaron búsquedas simultáneas de planteles juveniles usando filtros complejos.',mitigationApplied:'Caché semántica activada automáticamente para consultas repetidas de scouting.'},
{id:'anom_02',detectedAt:new Date(Date.now()-3600000*14).toISOString(),type:'FIRESTORE_READ_SPIKE',severity:'ALTA',title:'Aumento de Lecturas Firestore en Smart Feed (+210%)',metricVariation:'+210% lecturas sin paginado en Feed Público',aiCauseExplanation:'Navegación de usuarios no autenticados consumiendo publicaciones sin restricción de límite.',mitigationApplied:'Paginación estricta a limit(15) forzada en servidor express.'},
{id:'anom_03',detectedAt:new Date(Date.now()-3600000*36).toISOString(),type:'STORAGE_GROWTH',severity:'BAJA',title:'Crecimiento de Almacenamiento Multimedia HD (+3.2 GB)',metricVariation:'+3.2 GB en Firebase Storage en 24h',aiCauseExplanation:'Carga masiva de videos de jugadas destacadas por futbolistas verificados.',mitigationApplied:'Compresión WebP y transcodificación H.264 automática activada en subidas.'}];
const actionableRecommendations:ActionableRecommendation[]=[
{id:'rec_01',category:'IA_LIMITS',title:'Aumentar Límite Diario de Consultas IA en Coach Deportivo',impactEstimate:'+14% Retención | +$0.40 USD/mes costo',description:'Dado que el módulo Coach IA opera con un margen del 98%, elevar el límite diario de 20 a 35 consultas aumentará el engagement sin afectar las finanzas.',recommendedAction:'Aumentar el límite de consultas de IA para usuarios PRO.'},
{id:'rec_02',category:'PRECIOS',title:'Ajuste del Plan Premium Atleta de $14.900 a $18.500 ARS',impactEstimate:'+24% Incremento MRR (+~$105 USD/mes)',description:'El valor percibido por la plataforma permite un incremento del 24% sin disparar la tasa de Churn.',recommendedAction:'Actualizar el precio del Plan Premium en la pasarela de pagos.'},
{id:'rec_03',category:'COST_OPTIMIZATION',title:'Optimización de Exportación PDF HD para Eliminar Déficit',impactEstimate:'Ahorro de $0.80 USD/mes | Margen positivo',description:'El módulo de PDF genera $5.80 USD de costo y $5.00 USD de ingreso. Aplicando compresión vectorial de imágenes en servidor se elimina el déficit.',recommendedAction:'Activar compresión de imágenes en generación de PDF.'},
{id:'rec_04',category:'MARKETING',title:'Aumentar Inversión en Marketing de Adquisición',impactEstimate:'Retorno Estimado LTV/CAC: 8.6x',description:'El costo de adquisición ($12.50 USD) se recupera en solo 5.5 meses con un LTV de $108.08 USD, lo que justifica escalar pauta en redes sociales.',recommendedAction:'Duplicar presupuesto de adquisición enfocado en Clubes y Agentes.'}];
const businessHealthScore:BusinessHealthScore={overallScore:95,status:'EXCELENTE',components:{security:98,availability:99,profitability:97,growth:88,costControl:95,userSatisfaction:92,performance:94},summaryText:'La plataforma TalentMatch / ScoutAR se encuentra en estado EXCELENTE. Operación 100% autosostenible con margen bruto del 97% y cero riesgo financiero.'};
export interface FeatureProfitability { id:string; name:string; activeUsers:number; revenueUsd:number; revenueArs:number; totalCostUsd:number; aiCostUsd:number; firestoreCostUsd:number; storageCostUsd:number; cloudRunCostUsd:number; netProfitUsd:number; profitMarginPct:number; growthTrend:string; isDeficit:boolean; status:'PROFITABLE'|'DEFICIT'|'SUPPORT_COST'; }
export interface ReserveFundConfig { operationPct:number; growthPct:number; emergencyPct:number; operationalPoolUsd:number; growthPoolUsd:number; emergencyPoolUsd:number; }
export interface FinancialAlert { id:string; timestamp:string; priority:'ALTA'|'MEDIA'|'BAJA'; title:string; description:string; suggestedAction:string; }
const budgetConfig:BudgetConfig={monthlyBudgetUsd:50,dailyBudgetUsd:2.5,aiBudgetUsd:30,firestoreBudgetUsd:10,storageBudgetUsd:5,cloudRunBudgetUsd:5,freeUserDailyAiLimit:5,premiumUserDailyAiLimit:100,freeUserMonthlyAppLimit:20};
const reserveFundConfig:ReserveFundConfig={operationPct:70,growthPct:20,emergencyPct:10,operationalPoolUsd:304.85,growthPoolUsd:87.1,emergencyPoolUsd:43.55};
const featureProfitabilityData:FeatureProfitability[]=[
{id:'scout_ia',name:'Scout IA (Recomendador de Candidatos)',activeUsers:85,revenueUsd:185,revenueArs:240500,totalCostUsd:3.8,aiCostUsd:3.1,firestoreCostUsd:.4,storageCostUsd:0,cloudRunCostUsd:.3,netProfitUsd:181.2,profitMarginPct:97.9,growthTrend:'+18% (Alta Rentabilidad)',isDeficit:false,status:'PROFITABLE'},
{id:'coach_ia',name:'Coach Deportivo IA & Planes',activeUsers:62,revenueUsd:120,revenueArs:156000,totalCostUsd:2.4,aiCostUsd:1.9,firestoreCostUsd:.3,storageCostUsd:0,cloudRunCostUsd:.2,netProfitUsd:117.6,profitMarginPct:98,growthTrend:'+12%',isDeficit:false,status:'PROFITABLE'},
{id:'smart_feed',name:'Smart Feed Social & Videos',activeUsers:148,revenueUsd:60,revenueArs:78000,totalCostUsd:1.85,aiCostUsd:0,firestoreCostUsd:1.2,storageCostUsd:.45,cloudRunCostUsd:.2,netProfitUsd:58.15,profitMarginPct:96.9,growthTrend:'+5%',isDeficit:false,status:'PROFITABLE'},
{id:'chat_directo',name:'Chat Directo & Negociaciones',activeUsers:90,revenueUsd:40,revenueArs:52000,totalCostUsd:.9,aiCostUsd:0,firestoreCostUsd:.7,storageCostUsd:.2,cloudRunCostUsd:0,netProfitUsd:39.1,profitMarginPct:97.8,growthTrend:'+8%',isDeficit:false,status:'PROFITABLE'},
{id:'comparador_jugadores',name:'Comparador de Jugadores Head-to-Head',activeUsers:42,revenueUsd:25,revenueArs:32500,totalCostUsd:.65,aiCostUsd:.5,firestoreCostUsd:.15,storageCostUsd:0,cloudRunCostUsd:0,netProfitUsd:24.35,profitMarginPct:97.4,growthTrend:'+14%',isDeficit:false,status:'PROFITABLE'},
{id:'radar_talentos',name:'Radar de Talentos & Filtros Avanzados',activeUsers:55,revenueUsd:30,revenueArs:39000,totalCostUsd:.8,aiCostUsd:.6,firestoreCostUsd:.2,storageCostUsd:0,cloudRunCostUsd:0,netProfitUsd:29.2,profitMarginPct:97.3,growthTrend:'+10%',isDeficit:false,status:'PROFITABLE'},
{id:'reportes_pdf',name:'Exportación de Reportes PDF HD',activeUsers:18,revenueUsd:5,revenueArs:6500,totalCostUsd:5.8,aiCostUsd:0,firestoreCostUsd:.8,storageCostUsd:4,cloudRunCostUsd:1,netProfitUsd:-.8,profitMarginPct:-16,growthTrend:'-4% (En Déficit)',isDeficit:true,status:'DEFICIT'},
{id:'notificaciones_alertas',name:'Notificaciones & Alertas Email/Push',activeUsers:148,revenueUsd:0,revenueArs:0,totalCostUsd:.45,aiCostUsd:0,firestoreCostUsd:.2,storageCostUsd:0,cloudRunCostUsd:.25,netProfitUsd:-.45,profitMarginPct:0,growthTrend:'Estable (Soporte Base)',isDeficit:false,status:'SUPPORT_COST'}];
const financialAlerts:FinancialAlert[]=[
{id:'alert_001',timestamp:new Date(Date.now()-3600000*3).toISOString(),priority:'ALTA',title:'Funcionalidad en Déficit: Exportación PDF HD',description:'La generación de reportes PDF HD generó $5.80 USD de costo frente a solo $5.00 USD de ingresos atribuibles.',suggestedAction:'Aplicar compresión server-side de imágenes en los PDF o limitar a usuarios Plan PRO.'},
{id:'alert_002',timestamp:new Date(Date.now()-3600000*8).toISOString(),priority:'MEDIA',title:'Pico de Lecturas Firestore en Smart Feed',description:'Se detectó un aumento del 12% en lecturas no paginadas en Smart Feed por usuarios no autenticados.',suggestedAction:'Forzar paginación estricta a limit(15) en feed público para ahorrar ~$0.80 USD/mes.'},
{id:'alert_003',timestamp:new Date(Date.now()-3600000*24).toISOString(),priority:'BAJA',title:'Fondo de Emergencia Asignado Exitosamente',description:'Se ha reservado un 10% del MRR ($43.55 USD) en la subcuenta intocable de emergencia.',suggestedAction:'Ninguna acción requerida. Fondo protegido.'}];
const financialState:any={incomeMonthlyArs:566200,incomeMonthlyUsd:435.5,currentMonthSpendUsd:{ai:6.4,firestore:2.15,storage:.8,cloudRun:1.2,hosting:.5,notificationsEmail:.45,total:11.5},todaySpendUsd:{ai:.35,firestore:.12,storage:.04,cloudRun:.08,hosting:.02,notificationsEmail:.01,total:.62},totalsCounters:{aiCallsMonth:1240,aiTokensMonth:215000,firestoreReadsMonth:45200,firestoreWritesMonth:6800,storageBytesMonth:8.4*1024*1024*1024,activeFreeUsers:110,activePremiumUsers:38}};
const userCostMap=new Map<string,UserCostRecord>();
const seedUserStats:UserCostRecord[]=[
{userId:'usr_001',userEmail:'scout.boca@cabj.com.ar',role:'club',isPremium:true,aiCallsToday:18,aiCallsTotal:142,firestoreReads:1250,firestoreWrites:140,estimatedCostUsd:1.15,revenueGeneratedArs:49900,netProfitUsd:37.23,isDeficit:false,lastActive:'Hace 5 min'},
{userId:'usr_002',userEmail:'mateo.valdez@gmail.com',role:'atleta',isPremium:false,aiCallsToday:5,aiCallsTotal:48,firestoreReads:620,firestoreWrites:45,estimatedCostUsd:.38,revenueGeneratedArs:0,netProfitUsd:-.38,isDeficit:true,lastActive:'Hace 12 min'},
{userId:'usr_003',userEmail:'contacto@riverplate.com.ar',role:'club',isPremium:true,aiCallsToday:24,aiCallsTotal:210,firestoreReads:2400,firestoreWrites:310,estimatedCostUsd:1.85,revenueGeneratedArs:49900,netProfitUsd:36.53,isDeficit:false,lastActive:'Hace 2 min'},
{userId:'usr_004',userEmail:'lucas.gomez@hotmail.com',role:'atleta',isPremium:true,aiCallsToday:12,aiCallsTotal:86,firestoreReads:890,firestoreWrites:80,estimatedCostUsd:.72,revenueGeneratedArs:14900,netProfitUsd:10.74,isDeficit:false,lastActive:'Hace 45 min'},
{userId:'usr_005',userEmail:'bot_suspicious_99@temp.net',role:'atleta',isPremium:false,aiCallsToday:5,aiCallsTotal:120,firestoreReads:3100,firestoreWrites:190,estimatedCostUsd:1.45,revenueGeneratedArs:0,netProfitUsd:-1.45,isDeficit:true,lastActive:'Hace 1 hora'}];
seedUserStats.forEach(u=>userCostMap.set(u.userId,u));
const financialAuditLogs:FinancialAuditLog[]=[{id:'flog_101',timestamp:new Date(Date.now()-3600000*2).toISOString(),action:'REUTILIZACIÓN_DE_CACHÉ_IA',reason:'Consulta idéntica detectada para recomendación de candidatos en Santiago del Estero.',estimatedSavingsUsd:.0035,protectionLevel:'NORMAL'},{id:'flog_102',timestamp:new Date(Date.now()-3600000*5).toISOString(),action:'PAGINACIÓN_FIRME_FIRESTORE',reason:'Filtro aplicado en servidor con limit(20) reduciendo 850 lecturas innecesarias.',estimatedSavingsUsd:.0012,protectionLevel:'NORMAL'},{id:'flog_103',timestamp:new Date(Date.now()-3600000*12).toISOString(),action:'OPTIMIZACIÓN_DE_TOKENS_IA',reason:'Recorte automático de array de candidatos a 30 ítems para reducir consumo de tokens en Gemini.',estimatedSavingsUsd:.008,protectionLevel:'OPTIMIZING_75'}];
function getProtectionStatus(){const currentTotal=financialState.currentMonthSpendUsd.total;const budget=budgetConfig.monthlyBudgetUsd;const pct=Math.min(100,Math.round(currentTotal/budget*100));let status:'NORMAL'|'WARNING_50'|'OPTIMIZING_75'|'THROTTLING_90'|'PROTECTION_MODE_100'='NORMAL';if(pct>=100)status='PROTECTION_MODE_100';else if(pct>=90)status='THROTTLING_90';else if(pct>=75)status='OPTIMIZING_75';else if(pct>=50)status='WARNING_50';return{percentageSpent:pct,status,currentSpendUsd:currentTotal,budgetUsd:budget};}
function addFinancialAuditLog(action:string,reason:string,estimatedSavingsUsd:number){financialAuditLogs.unshift({id:`flog_${Date.now()}_${Math.random().toString(36).substring(2,6)}`,timestamp:new Date().toISOString(),action,reason,estimatedSavingsUsd,protectionLevel:getProtectionStatus().status});if(financialAuditLogs.length>100)financialAuditLogs.pop();}
function trackUserUsage(userId:string,userEmail?:string,role?:string,isPremium?:boolean,costUsd=.0025,aiCalls=1,reads=0,writes=0){const uid=userId||'usr_anonymous';const existing=userCostMap.get(uid)||{userId:uid,userEmail:userEmail||`user_${uid.slice(0,6)}@talentmatch.ar`,role:role||'atleta',isPremium:!!isPremium,aiCallsToday:0,aiCallsTotal:0,firestoreReads:0,firestoreWrites:0,estimatedCostUsd:0,revenueGeneratedArs:isPremium?14900:0,netProfitUsd:isPremium?11.46:0,isDeficit:false,lastActive:'Ahora mismo'};existing.aiCallsToday+=aiCalls;existing.aiCallsTotal+=aiCalls;existing.firestoreReads+=reads;existing.firestoreWrites+=writes;existing.estimatedCostUsd=parseFloat((existing.estimatedCostUsd+costUsd).toFixed(4));existing.netProfitUsd=parseFloat(((existing.revenueGeneratedArs/1300)-existing.estimatedCostUsd).toFixed(2));existing.isDeficit=existing.netProfitUsd<0;existing.lastActive='Ahora mismo';userCostMap.set(uid,existing);financialState.currentMonthSpendUsd.ai+=costUsd;financialState.currentMonthSpendUsd.total+=costUsd;financialState.todaySpendUsd.ai+=costUsd;financialState.todaySpendUsd.total+=costUsd;financialState.totalsCounters.aiCallsMonth+=aiCalls;}
const getGeminiClient=()=>{const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return null;return new GoogleGenAI({apiKey,httpOptions:{headers:{'User-Agent':'aistudio-build'}}});};

app.get('/api/health',(_req,res)=>res.json({status:'ok',timestamp:new Date().toISOString()}));
app.get('/api/financial/summary',(_req,res)=>{const protection=getProtectionStatus();const userList=Array.from(userCostMap.values());const topConsumingUsers=[...userList].sort((a,b)=>b.estimatedCostUsd-a.estimatedCostUsd).slice(0,10);const deficitUsers=userList.filter(u=>u.isDeficit);const currentDay=new Date().getDate();const totalDaysMonth=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate();const eodProjectedCostUsd=parseFloat((financialState.todaySpendUsd.total*(24/Math.max(1,new Date().getHours()))).toFixed(2));const monthlyProjectedCostUsd=parseFloat(((financialState.currentMonthSpendUsd.total/Math.max(1,currentDay))*totalDaysMonth).toFixed(2));const annualProjectedCostUsd=parseFloat((monthlyProjectedCostUsd*12).toFixed(2));const grossProfitUsd=parseFloat((financialState.incomeMonthlyUsd-financialState.currentMonthSpendUsd.total).toFixed(2));const netProfitMarginPct=financialState.incomeMonthlyUsd>0?Math.round(grossProfitUsd/financialState.incomeMonthlyUsd*100):0;const totalIncomeUsd=financialState.incomeMonthlyUsd;reserveFundConfig.operationalPoolUsd=parseFloat((totalIncomeUsd*reserveFundConfig.operationPct/100).toFixed(2));reserveFundConfig.growthPoolUsd=parseFloat((totalIncomeUsd*reserveFundConfig.growthPct/100).toFixed(2));reserveFundConfig.emergencyPoolUsd=parseFloat((totalIncomeUsd*reserveFundConfig.emergencyPct/100).toFixed(2));const financialForecast={days30:{incomeUsd:totalIncomeUsd,costsUsd:monthlyProjectedCostUsd,cashFlowUsd:parseFloat((totalIncomeUsd-monthlyProjectedCostUsd).toFixed(2)),incomeArs:Math.round(totalIncomeUsd*1300)},days90:{incomeUsd:parseFloat((totalIncomeUsd*3.1).toFixed(2)),costsUsd:parseFloat((monthlyProjectedCostUsd*3.1).toFixed(2)),cashFlowUsd:parseFloat(((totalIncomeUsd-monthlyProjectedCostUsd)*3.1).toFixed(2)),incomeArs:Math.round(totalIncomeUsd*3.1*1300)},days365:{incomeUsd:parseFloat((totalIncomeUsd*14.2).toFixed(2)),costsUsd:parseFloat((monthlyProjectedCostUsd*14.2).toFixed(2)),cashFlowUsd:parseFloat((totalIncomeUsd*14.2-monthlyProjectedCostUsd*14.2).toFixed(2)),incomeArs:Math.round(totalIncomeUsd*14.2*1300)}};res.json({timestamp:new Date().toISOString(),budgetConfig,financialState,reserveFundConfig,featureProfitability:featureProfitabilityData,financialAlerts,protectionStatus:protection,unitEconomics:unitEconomicsData,anomalies:anomalyDetections,forecasts:financialForecast,recommendations:actionableRecommendations,healthScore:businessHealthScore,projections:{eodProjectedCostUsd,monthlyProjectedCostUsd,annualProjectedCostUsd,grossProfitUsd,grossProfitArs:Math.round(grossProfitUsd*1300),netProfitMarginPct,breakEvenMonthlyUsers:10,costPerUserUsd:parseFloat((financialState.currentMonthSpendUsd.total/Math.max(1,userList.length)).toFixed(4)),costPerAiQueryUsd:.0025},topConsumingUsers,deficitUsersCount:deficitUsers.length,auditLogs:financialAuditLogs.slice(0,20)});});
app.post('/api/financial/reserve-config',(req,res)=>{const{operationPct,growthPct,emergencyPct}=req.body;if(operationPct===undefined||growthPct===undefined||emergencyPct===undefined)return res.status(400).json({error:'Porcentajes requeridos.'});const sum=Number(operationPct)+Number(growthPct)+Number(emergencyPct);if(Math.abs(sum-100)>.1)return res.status(400).json({error:'La suma de porcentajes debe ser exactamente 100%.'});reserveFundConfig.operationPct=Number(operationPct);reserveFundConfig.growthPct=Number(growthPct);reserveFundConfig.emergencyPct=Number(emergencyPct);addFinancialAuditLog('REPARTICIÓN_FONDO_RESERVA',`Fondo Inteligente ajustado: ${operationPct}% Operativo, ${growthPct}% Crecimiento, ${emergencyPct}% Emergencia (Intocable).`,0);return res.json({success:true,reserveFundConfig,message:'Fondo de Reserva Inteligente actualizado.'});});
app.post('/api/financial/simulate-growth',(req,res)=>{const{additionalUsers=1000,aiMultiplier=1,firestorePriceMultiplier=1,conversionRatePct=3.5}=req.body;const currentActiveUsers=financialState.totalsCounters.activeFreeUsers+financialState.totalsCounters.activePremiumUsers;const newTotalUsers=currentActiveUsers+Number(additionalUsers);const estimatedNewPremiumUsers=Math.round(newTotalUsers*(Number(conversionRatePct)/100));const estimatedMonthlyIncomeUsd=estimatedNewPremiumUsers*14900/1300;const projectedAiCostUsd=newTotalUsers*.04*Number(aiMultiplier);const projectedDbCostUsd=newTotalUsers*.015*Number(firestorePriceMultiplier);const projectedInfraCostUsd=newTotalUsers*.02;const projectedTotalCostUsd=projectedAiCostUsd+projectedDbCostUsd+projectedInfraCostUsd;const projectedGrossProfitUsd=estimatedMonthlyIncomeUsd-projectedTotalCostUsd;const breakEvenUsersNeeded=Math.ceil(projectedTotalCostUsd/(14900/1300));const risks:string[]=[];const recommendations:string[]=[];if(projectedTotalCostUsd>budgetConfig.monthlyBudgetUsd){risks.push(`Supera el presupuesto mensual configurado ($${budgetConfig.monthlyBudgetUsd} USD).`);recommendations.push('Aumentar el límite de presupuesto mensual o activar la paginación estricta.');}if(estimatedMonthlyIncomeUsd<projectedTotalCostUsd){risks.push('Escenario con margen negativo (Déficit operacional).');recommendations.push('Mejorar la tasa de conversión a Plan PRO a más del 5% o incrementar el costo del plan.');}else recommendations.push('Escenario altamente rentable. Mantener política actual de caching e IA.');res.json({scenario:{additionalUsers,aiMultiplier,firestorePriceMultiplier,conversionRatePct},results:{newTotalUsers,estimatedNewPremiumUsers,projectedMonthlyIncomeUsd:parseFloat(estimatedMonthlyIncomeUsd.toFixed(2)),projectedMonthlyIncomeArs:Math.round(estimatedMonthlyIncomeUsd*1300),projectedCosts:{aiUsd:parseFloat(projectedAiCostUsd.toFixed(2)),firestoreUsd:parseFloat(projectedDbCostUsd.toFixed(2)),storageCloudRunUsd:parseFloat(projectedInfraCostUsd.toFixed(2)),totalUsd:parseFloat(projectedTotalCostUsd.toFixed(2))},projectedGrossProfitUsd:parseFloat(projectedGrossProfitUsd.toFixed(2)),projectedGrossProfitArs:Math.round(projectedGrossProfitUsd*1300),breakEvenUsersNeeded,netProfitMarginPct:estimatedMonthlyIncomeUsd>0?Math.round(projectedGrossProfitUsd/estimatedMonthlyIncomeUsd*100):0,risks,recommendations}});});
app.post('/api/financial/simulate-pricing',(req,res)=>{const{monthlySubArs=14900,annualSubArs=129000,clubSubArs=49900,freeAiDailyLimit=5,projectedSubscribers=50}=req.body;const monthlySubUsd=Number(monthlySubArs)/1300;const estimatedMrrArs=Number(projectedSubscribers)*Number(monthlySubArs)+(5*Number(clubSubArs));const estimatedMrrUsd=estimatedMrrArs/1300;const currentTotalCostUsd=financialState.currentMonthSpendUsd.total;const netProfitUsd=estimatedMrrUsd-currentTotalCostUsd;const breakEvenSubscribers=Math.ceil(currentTotalCostUsd/monthlySubUsd);res.json({pricingConfig:{monthlySubArs,annualSubArs,clubSubArs,freeAiDailyLimit,projectedSubscribers},results:{estimatedMrrArs,estimatedMrrUsd:parseFloat(estimatedMrrUsd.toFixed(2)),currentTotalCostUsd:parseFloat(currentTotalCostUsd.toFixed(2)),netProfitUsd:parseFloat(netProfitUsd.toFixed(2)),netProfitArs:Math.round(netProfitUsd*1300),breakEvenSubscribers,profitMarginPct:estimatedMrrUsd>0?Math.round(netProfitUsd/estimatedMrrUsd*100):0,recommendation:netProfitUsd>0?'Modelo comercial sostenible con alto margen de retorno.':'Revisar precios hacia arriba para asegurar punto de equilibrio.'}});});
app.get('/api/financial/executive-report',(req,res)=>{const period=(req.query.period as string)||'monthly';res.json({generatedAt:new Date().toISOString(),period:period.toUpperCase(),title:`Informe Ejecutivo de FinOps & Rentabilidad TalentMatch (${period.toUpperCase()})`,financialSummary:{incomeArs:financialState.incomeMonthlyArs,incomeUsd:financialState.incomeMonthlyUsd,expensesUsd:financialState.currentMonthSpendUsd.total,netProfitUsd:parseFloat((financialState.incomeMonthlyUsd-financialState.currentMonthSpendUsd.total).toFixed(2)),profitMarginPct:Math.round((financialState.incomeMonthlyUsd-financialState.currentMonthSpendUsd.total)/financialState.incomeMonthlyUsd*100),reserveAllocation:{operation:reserveFundConfig.operationalPoolUsd,growth:reserveFundConfig.growthPoolUsd,emergency:reserveFundConfig.emergencyPoolUsd}},topProfitableFeatures:featureProfitabilityData.filter(f=>!f.isDeficit),deficitFeatures:featureProfitabilityData.filter(f=>f.isDeficit),savingsFromOptimizationsUsd:financialAuditLogs.reduce((a,l)=>a+l.estimatedSavingsUsd,0),strategicRecommendations:['Mantener el tope presupuestario mensual de $50 USD.','Optimizar la generación de reportes PDF HD aplicando compresión de imágenes.','Promover la conversión del plan de clubes ($49.900 ARS/mes) para maximizar la reserva de emergencia.']});});

function aiFallbackProfile(a:any){return{report:{athleteId:a.id,summary:`${a.name} es un deportista con sólida base en ${a.sport} (${a.position}). Muestra excelente constancia en ${a.city}.`,strengths:['Juego físico en el mano a mano','Dominio de la posición','Disciplinado en entrenamientos'],areasToImprove:['Toma de decisiones bajo alta presión','Técnica de pie no hábil'],suggestedLevel:a.level==='Amateur'?'Liga Regional / Torneo Local':'Semiprofesional / Federal',overallRating:8.5,keyStatsAnalysis:`Muestra regularidad con ${a.stats?.matchesPlayed||20} partidos disputados y métricas destacadas.`}};}

app.post('/api/ai/match-candidates',async(req,res)=>{try{const{search,athletes}=req.body;if(!search||!Array.isArray(athletes))return res.status(400).json({error:'Faltan datos de búsqueda o atletas.'});const candidates=(await getAuthoritativeCandidates(athletes)).slice(0,30);const key=generateCacheKey('/api/ai/match-candidates',{search,ids:candidates.map(a=>a.id)},req.user?.uid);const cached=getCachedAIResponse(key);if(cached)return res.json(cached);const ai=getGeminiClient();if(!ai){const matches=candidates.map((ath:any)=>{let score=60;const reasons:string[]=[];if(ath.sport.toLowerCase()===search.sport.toLowerCase()){score+=20;reasons.push(`Mismo deporte (${ath.sport})`);}else score-=30;if(ath.position.toLowerCase().includes(String(search.positionNeeded||'').toLowerCase())){score+=15;reasons.push(`Posición exacta (${ath.position})`);}if(ath.age>=search.minAge&&ath.age<=search.maxAge){score+=10;reasons.push(`Rango de edad ideal (${ath.age} años)`);}if(ath.province.toLowerCase()===String(search.province||'').toLowerCase()||ath.city.toLowerCase()===String(search.city||'').toLowerCase()){score+=10;reasons.push(`Ubicación cercana (${ath.city}, ${ath.province})`);}score=Math.min(99,Math.max(30,score));return{athleteId:ath.id,score,keyReasons:reasons.length?reasons:['Perfil compatible en nivel general'],tacticalAnalysis:`El perfil de ${ath.name} cumple con los requerimientos básicos de ${search.clubName}.`,recommendedRole:score>80?'Titular / Refuerzo Directo':'Candidato a Evaluación en Pruebas'};});const out={matches};setCachedAIResponse(key,out);return res.json(out);}const prompt=`Eres un Director Deportivo, Jefe de Scouting y Reclutador de Red Profesional de Talento Deportivo en Argentina y Latinoamérica. Evalúa candidatos para esta búsqueda: ${JSON.stringify(search)}. Candidatos: ${JSON.stringify(candidates.map((a:any)=>({id:a.id,name:a.name,sport:a.sport,position:a.position,age:a.age,city:a.city,province:a.province,level:a.level,bio:a.bio,isVerified:a.isVerified,trustScore:a.trustScore})),null,2)}. Devuelve score 0-100, razones, análisis y rol recomendado.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{matches:{type:Type.ARRAY,items:{type:Type.OBJECT,properties:{athleteId:{type:Type.STRING},score:{type:Type.INTEGER},keyReasons:{type:Type.ARRAY,items:{type:Type.STRING}},tacticalAnalysis:{type:Type.STRING},recommendedRole:{type:Type.STRING}},required:['athleteId','score','keyReasons','tacticalAnalysis','recommendedRole']}}},required:['matches']}}});const parsed=JSON.parse(response.text||'{}');setCachedAIResponse(key,parsed);return res.json(parsed);}catch(error:any){console.error('Error in /api/ai/match-candidates:',error);return res.status(500).json({error:'Error procesando recomendación con IA',details:error.message});}});

app.post('/api/ai/scout-report',async(req,res)=>{try{const{athlete}=req.body;if(!athlete)return res.status(400).json({error:'Faltan datos del atleta.'});const a=await getAuthoritativeAthlete(athlete);const ai=getGeminiClient();if(!ai)return res.json(aiFallbackProfile(a));const prompt=`Eres un Director Deportivo y Auditor de Talento Profesional. Genera un reporte técnico para: ${JSON.stringify({name:a.name,sport:a.sport,position:a.position,age:a.age,level:a.level,city:a.city,province:a.province,availability:a.availability,verification:a.isVerified,trustScore:a.trustScore,bio:a.bio,stats:a.stats,workHistory:a.workHistory||[]})}. Devuelve resumen, fortalezas, aspectos a mejorar, nivel recomendado, nota 1-10 y análisis de trayectoria.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{report:{type:Type.OBJECT,properties:{athleteId:{type:Type.STRING},summary:{type:Type.STRING},strengths:{type:Type.ARRAY,items:{type:Type.STRING}},areasToImprove:{type:Type.ARRAY,items:{type:Type.STRING}},suggestedLevel:{type:Type.STRING},overallRating:{type:Type.NUMBER},keyStatsAnalysis:{type:Type.STRING}},required:['athleteId','summary','strengths','areasToImprove','suggestedLevel','overallRating','keyStatsAnalysis']}},required:['report']}}});return res.json(JSON.parse(response.text||'{}'));}catch(error:any){console.error('Error in /api/ai/scout-report:',error);return res.status(500).json({error:'Error generando informe de scouting con IA',details:error.message});}});

app.post('/api/ai/compare-candidates',async(req,res)=>{try{const{candidates,searchContext}=req.body;if(!Array.isArray(candidates)||candidates.length===0)return res.status(400).json({error:'Debe enviar candidatos para comparar.'});const list=await getAuthoritativeCandidates(candidates);const ai=getGeminiClient();if(!ai){const top=list[0];return res.json({comparison:{candidateIds:list.map(c=>c.id),recommendedSelectionId:top?.id||'',aiStrategicConclusion:top?`${top.name} presenta el perfil con mayor solidez según los datos disponibles.`:'No hay candidatos suficientes.',summaryByCandidate:Object.fromEntries(list.map((c:any)=>[c.id,{strengths:[`Perfil ${c.verificationTier||'Estándar'}`,`Ubicado en ${c.city}, ${c.province}`],weaknesses:['Requiere evaluación adicional'],fitRating:c.id===top?.id?'95%':'85%',idealRole:c.id===top?.id?'Titular Inmediato':'Alternativa de Valor'}]))}});}const prompt=`Compara candidatos para ${JSON.stringify(searchContext||{})}: ${JSON.stringify(list.map((c:any)=>({id:c.id,name:c.name,sport:c.sport,position:c.position,age:c.age,level:c.level,trustScore:c.trustScore,rating:c.rating,stats:c.stats})),null,2)}. Devuelve JSON con comparison, candidateIds, recommendedSelectionId, aiStrategicConclusion y summaryByCandidate.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{comparison:{type:Type.OBJECT,properties:{candidateIds:{type:Type.ARRAY,items:{type:Type.STRING}},recommendedSelectionId:{type:Type.STRING},aiStrategicConclusion:{type:Type.STRING},summaryByCandidate:{type:Type.OBJECT}},required:['candidateIds','recommendedSelectionId','aiStrategicConclusion']}},required:['comparison']}}});return res.json(JSON.parse(response.text||'{}'));}catch(error:any){console.error('Error in /api/ai/compare-candidates:',error);return res.status(500).json({error:'Error realizando comparativa con IA',details:error.message});}});

app.post('/api/ai/smart-search',async(req,res)=>{try{const{queryPrompt,athletes}=req.body;if(!queryPrompt||!athletes)return res.status(400).json({error:'Falta la consulta de búsqueda.'});const list=await getAuthoritativeCandidates(athletes);const ai=getGeminiClient();if(!ai){const q=String(queryPrompt).toLowerCase();const filtered=list.filter((a:any)=>a.sport.toLowerCase().includes(q)||a.position.toLowerCase().includes(q)||a.city.toLowerCase().includes(q)||a.province.toLowerCase().includes(q));return res.json({matches:(filtered.length?filtered:list).map((a:any,i)=>({athleteId:a.id,relevanceScore:Math.max(20,90-i*5),matchReason:`Coincidencia encontrada para ${a.sport} (${a.position})`})),summaryReasoning:'Búsqueda por palabras clave finalizada.'});}const prompt=`Analiza la búsqueda del reclutador: "${queryPrompt}". Catálogo: ${JSON.stringify(list.map((a:any)=>({id:a.id,name:a.name,sport:a.sport,position:a.position,age:a.age,city:a.city,province:a.province,level:a.level,bio:a.bio,isVerified:a.isVerified,trustScore:a.trustScore})),null,2)}. Devuelve matches ordenados con relevanceScore 0-100, matchReason y summaryReasoning.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{summaryReasoning:{type:Type.STRING},matches:{type:Type.ARRAY,items:{type:Type.OBJECT,properties:{athleteId:{type:Type.STRING},relevanceScore:{type:Type.INTEGER},matchReason:{type:Type.STRING}},required:['athleteId','relevanceScore','matchReason']}}},required:['summaryReasoning','matches']}}});return res.json(JSON.parse(response.text||'{}'));}catch(error:any){console.error('Error in /api/ai/smart-search:',error);return res.status(500).json({error:'Error procesando búsqueda inteligente',details:error.message});}});

app.post('/api/ai/generate-search-description',async(req,res)=>{try{const{clubName,sport,positionNeeded,minAge,maxAge,city,levelRequired}=req.body;const ai=getGeminiClient();if(!ai)return res.json({description:`${clubName} abre convocatoria para incorporar ${positionNeeded} de ${minAge} a ${maxAge} años en la ciudad de ${city}. Buscamos deportistas de nivel ${levelRequired} con compromiso y visión de desarrollo.`,requirements:[`Edad entre ${minAge} y ${maxAge} años`,`Experiencia en ${sport} categoría ${levelRequired}`,`Disponibilidad para pruebas presenciales en ${city}`]});const prompt=`Genera una convocatoria profesional para ${clubName}, deporte ${sport}, posición ${positionNeeded}, edad ${minAge}-${maxAge}, ciudad ${city}, nivel ${levelRequired}. Devuelve description y requirements.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{description:{type:Type.STRING},requirements:{type:Type.ARRAY,items:{type:Type.STRING}}},required:['description','requirements']}}});return res.json(JSON.parse(response.text||'{}'));}catch(error:any){console.error('Error in /api/ai/generate-search-description:',error);return res.status(500).json({error:'Error redactando convocatoria',details:error.message});}});

app.post('/api/ai/generate-athlete-profile',async(req,res)=>{try{const{name,sport,position,age,level,athleteNotes}=req.body;const ai=getGeminiClient();if(!ai)return res.json({bio:`${name||'Deportista'} es un ${position||'jugador'} de ${sport||'deporte'} (${age||20} años) con visión técnica y constancia. ${athleteNotes||'Enfocado en su desarrollo físico y táctico para competir al máximo nivel.'}`,sportsExperience:`Trayectoria en ${sport}: ${athleteNotes||'Múltiples temporadas disputadas en ligas locales con destacado rendimiento.'}`,keyAchievements:[`Formación continua en ${sport} posición ${position||'destacada'}`,`Regularidad en torneos locales y regionales (${level||'Liga Local'})`,'Liderazgo y trabajo en equipo comprobado']});const prompt=`Redacta ficha profesional de atleta. Datos: ${JSON.stringify({name,sport,position,age,level,athleteNotes})}. Devuelve bio, sportsExperience y keyAchievements.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{bio:{type:Type.STRING},sportsExperience:{type:Type.STRING},keyAchievements:{type:Type.ARRAY,items:{type:Type.STRING}}},required:['bio','sportsExperience','keyAchievements']}}});return res.json(JSON.parse(response.text||'{}'));}catch(error:any){console.error('Error in /api/ai/generate-athlete-profile:',error);return res.status(500).json({error:'Error generando ficha de atleta con IA',details:error.message});}});

app.post('/api/ai/generate-training-routine',async(req,res)=>{try{const{name,sport,position,level,areasToImprove}=req.body;const ai=getGeminiClient();if(!ai)return res.json({routineTitle:`Rutina de Alto Rendimiento para ${position||'Jugador'} (${sport||'Deporte'})`,weeklyFocus:'Potencia explosiva, agilidad técnica y toma de decisiones tácticas en alta intensidad.',drills:[{name:'Circuito de Agilidad y Cambio de Dirección',duration:'20 min',instructions:'Sprints de 10m con conos en Z, enfoque en desaceleración y primer paso explosivo.'},{name:'Drill Técnico Específico de Posición',duration:'25 min',instructions:'Repeticiones de pases bajo presión y control orientado.'},{name:'Trabajo Físico y Resistencia Anaeróbica',duration:'15 min',instructions:'Intervalos 30s máxima intensidad x 30s pausa activa.'}],recoveryTip:'Priorizar hidratación y estiramientos activos post-sesión.'});const prompt=`Crea plan de entrenamiento individualizado: ${JSON.stringify({name,sport,position,level,areasToImprove})}. Devuelve routineTitle, weeklyFocus, drills y recoveryTip.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{routineTitle:{type:Type.STRING},weeklyFocus:{type:Type.STRING},drills:{type:Type.ARRAY,items:{type:Type.OBJECT,properties:{name:{type:Type.STRING},duration:{type:Type.STRING},instructions:{type:Type.STRING}},required:['name','duration','instructions']}},recoveryTip:{type:Type.STRING}},required:['routineTitle','weeklyFocus','drills','recoveryTip']}}});return res.json(JSON.parse(response.text||'{}'));}catch(error:any){console.error('Error in /api/ai/generate-training-routine:',error);return res.status(500).json({error:'Error generando rutina de entrenamiento',details:error.message});}});

app.post('/api/ai/athlete-coach',async(req,res)=>{try{const{athlete,question}=req.body;if(!athlete||!question)return res.status(400).json({error:'Faltan datos de atleta o la pregunta.'});const a=await getAuthoritativeAthlete(athlete);const ai=getGeminiClient();if(!ai)return res.json({answer:`Hola ${a.name}. Analizando tu perfil de ${a.sport} (${a.position}, ${a.age} años, nivel ${a.level}): tu perfil muestra fortalezas sólidas.`,strengths:['Regularidad en partidos jugados','Formación en la posición','Ubicación estratégica'],weaknesses:['Le falta cargar más videos en HD','Verificación documental aún no completada'],competitiveLevel:a.level==='Amateur'?'Liga Regional':'Federal A / Semiprofesional',hiringProbability:78,priorityActions:['Subir un video corto de jugadas destacadas','Completar verificación de identidad','Solicitar una referencia a un ex entrenador']});const prompt=`Actúa como Coach Deportivo. Datos del atleta: ${JSON.stringify(a)}. Pregunta: "${question}". Responde en JSON con answer, strengths, weaknesses, competitiveLevel, hiringProbability y priorityActions.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{answer:{type:Type.STRING},strengths:{type:Type.ARRAY,items:{type:Type.STRING}},weaknesses:{type:Type.ARRAY,items:{type:Type.STRING}},competitiveLevel:{type:Type.STRING},hiringProbability:{type:Type.INTEGER},priorityActions:{type:Type.ARRAY,items:{type:Type.STRING}}},required:['answer','strengths','weaknesses','competitiveLevel','hiringProbability','priorityActions']}}});return res.json(JSON.parse(response.text||'{}'));}catch(error:any){console.error('Error in /api/ai/athlete-coach:',error);return res.status(500).json({error:'Error procesando Coach IA',details:error.message});}});

app.post('/api/ai/club-scout-assistant',async(req,res)=>{try{const{queryPrompt,candidates,clubName}=req.body;if(!queryPrompt||!Array.isArray(candidates))return res.status(400).json({error:'Faltan datos de consulta o candidatos.'});const list=await getAuthoritativeCandidates(candidates);const ai=getGeminiClient();if(!ai)return res.json({executiveRecommendation:`Tras filtrar el catálogo de talentos para ${clubName||'el club'} según la búsqueda "${queryPrompt}", se detectaron ${list.length} perfiles compatibles.`,topMatches:list.slice(0,3).map((c:any,i)=>({candidateId:c.id,candidateName:c.name,compatibilityScore:95-i*4,keyReason:`Coincidencia técnica con la posición ${c.position} en ${c.city}`,recommendedRole:i===0?'Titular / Refuerzo Directo':'Alternativa de Valor'}))});const prompt=`Eres Scout IA Jefe para ${clubName||'Club Deportivo'}. Búsqueda: "${queryPrompt}". Candidatos: ${JSON.stringify(list.map((c:any)=>({id:c.id,name:c.name,sport:c.sport,position:c.position,age:c.age,city:c.city,province:c.province,level:c.level,isVerified:c.isVerified,trustScore:c.trustScore,rating:c.rating})),null,2)}. Devuelve executiveRecommendation y topMatches.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt,config:{responseMimeType:'application/json',responseSchema:{type:Type.OBJECT,properties:{executiveRecommendation:{type:Type.STRING},topMatches:{type:Type.ARRAY,items:{type:Type.OBJECT,properties:{candidateId:{type:Type.STRING},candidateName:{type:Type.STRING},compatibilityScore:{type:Type.INTEGER},keyReason:{type:Type.STRING},recommendedRole:{type:Type.STRING}},required:['candidateId','candidateName','compatibilityScore','keyReason','recommendedRole']}}},required:['executiveRecommendation','topMatches']}}});return res.json(JSON.parse(response.text||'{}'));}catch(error:any){console.error('Error in /api/ai/club-scout-assistant:',error);return res.status(500).json({error:'Error procesando Scout IA para Clubes',details:error.message});}});

app.post('/api/mercadopago/validate-coupon',(req,res)=>{const{code,originalPrice}=req.body;if(!code)return res.status(400).json({error:'Código no proporcionado.'});const cleanCode=String(code).trim().toUpperCase();let discountPercent=0;let description='';if(['TALENT100','PROMO100','PRUEBA100'].includes(cleanCode)){discountPercent=100;description='Cupón Especial 100% Bonificado (Acceso Gratuito de Prueba)';}else if(['PROMO50','ARGENTINA50'].includes(cleanCode)){discountPercent=50;description='Descuento del 50% en tu primera suscripción';}else if(['PRO2025','CLUB30'].includes(cleanCode)){discountPercent=30;description='Descuento del 30% en planes anuales/mensuales';}else if(cleanCode==='TALENT20'){discountPercent=20;description='Descuento de bienvenida del 20%';}else return res.status(404).json({valid:false,error:'Cupón no válido o expirado.'});const numericPrice=parseFloat(String(originalPrice).replace(/[^0-9.]/g,''))||14900;const finalPriceVal=Math.max(0,Math.round(numericPrice*(1-discountPercent/100)));res.json({valid:true,code:cleanCode,discountPercent,description,originalPrice:`$${numericPrice.toLocaleString('es-AR')} ARS`,finalPrice:`$${finalPriceVal.toLocaleString('es-AR')} ARS`,finalPriceNumeric:finalPriceVal});});
app.post('/api/mercadopago/create-preference',async(req,res)=>{try{const{planId,planName,priceMonthly,userEmail,userId,couponCode}=req.body;const numericPrice=parseFloat(String(priceMonthly).replace(/[^0-9.]/g,''))||14900;let finalPrice=numericPrice;let appliedCoupon=null;if(couponCode){const c=String(couponCode).trim().toUpperCase();if(['TALENT100','PROMO100','PRUEBA100'].includes(c)){finalPrice=0;appliedCoupon=c;}else if(['PROMO50','ARGENTINA50'].includes(c)){finalPrice=Math.round(numericPrice*.5);appliedCoupon=c;}else if(['PRO2025','CLUB30'].includes(c)){finalPrice=Math.round(numericPrice*.7);appliedCoupon=c;}}if(finalPrice===0)return res.status(400).json({error:'El cupón bonificado requiere un flujo de activación promocional seguro y no genera una preferencia de pago.'});const accessToken=process.env.MERCADOPAGO_ACCESS_TOKEN;if(!accessToken)return res.status(503).json({error:'Mercado Pago no está configurado en el servidor.'});const notificationUrl=`${req.protocol}://${req.get('host')}/api/mercadopago/webhook`;const backUrl=`${req.protocol}://${req.get('host')}?payment_status=approved`;const preferenceData={items:[{id:planId||'plan-pro',title:`TalentMatch - Suscripción ${planName||'PRO'}`,description:`Acceso Premium TalentMatch Argentina por 30 días (${userEmail||'usuario'})`,quantity:1,currency_id:'ARS',unit_price:finalPrice}],payer:{email:userEmail||'comprador@talentmatch.com.ar'},back_urls:{success:backUrl,pending:backUrl,failure:`${req.protocol}://${req.get('host')}?payment_status=failure`},auto_return:'approved',notification_url:notificationUrl,external_reference:JSON.stringify({userId,planId,planName,price:finalPrice,coupon:appliedCoupon})};const mpResponse=await fetch('https://api.mercadopago.com/checkout/preferences',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify(preferenceData)});const mpData=await mpResponse.json();if(!mpResponse.ok||!mpData.id)return res.status(502).json({error:'Mercado Pago no pudo crear una preferencia de pago.'});return res.json({preferenceId:mpData.id,init_point:mpData.init_point||mpData.sandbox_init_point,finalPrice:`$${finalPrice.toLocaleString('es-AR')} ARS`});}catch(err:any){console.error('Error in /api/mercadopago/create-preference:',err);return res.status(500).json({error:'Error al generar preferencia en Mercado Pago'});}});
app.post('/api/mercadopago/webhook',async(req,res)=>{
  try {
    const paymentId=String(req.body?.data?.id||req.query?.['data.id']||'').trim();
    const accessToken=process.env.MERCADOPAGO_ACCESS_TOKEN;
    if(!paymentId||!accessToken)return res.status(400).json({error:'Notificación de pago incompleta.'});
    const response=await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(paymentId)}`,{headers:{Authorization:`Bearer ${accessToken}`}});
    if(!response.ok)return res.status(502).json({error:'No se pudo verificar el pago con Mercado Pago.'});
    const payment=await response.json();
    const externalReference=String(payment.external_reference||'');
    let reference:any={};
    try{reference=JSON.parse(externalReference);}catch{reference={};}
    const uid=String(reference.userId||'');
    const transactionAmount=Number(payment.transaction_amount);
    const referencedPrice=Number(reference.price);
    const coupon=String(reference.coupon||'').trim().toUpperCase();
    const canonicalBasePrice=resolveCanonicalBasePrice(referencedPrice,coupon);
    if(payment.status!=='approved'||!uid||canonicalBasePrice===null)return res.status(200).json({status:'ignored',reason:'payment_not_approved_or_reference_invalid'});
    if(coupon==='TALENT100'||coupon==='PROMO100')return res.status(200).json({status:'ignored',reason:'zero_value_coupon_not_eligible'});
    const expectedFinalPrice=calculateCouponPrice(canonicalBasePrice,coupon).finalPrice;
    if(transactionAmount!==expectedFinalPrice||referencedPrice!==expectedFinalPrice)return res.status(200).json({status:'ignored',reason:'amount_mismatch'});
    const db=(admin as any).firestore();
    const userRef=db.collection('users').doc(uid);
    await db.runTransaction(async(transaction:any)=>{
      const userSnap=await transaction.get(userRef);
      if(!userSnap.exists)throw new Error('PAYMENT_USER_NOT_FOUND');
      transaction.set(userRef,{isPremium:true,premium:true,plan:'PRO',subscriptionPlanId:reference.planId||null,premiumActivatedAt:(admin as any).firestore.FieldValue.serverTimestamp(),premiumPaymentId:String(payment.id),premiumAmountArs:transactionAmount,premiumCoupon:coupon||null,premiumSource:'mercadopago'},{merge:true});
    });
    invalidatePremiumEntitlement(uid);
    const eventRef=req.mercadoPagoWebhookEventRef;
    if(eventRef)await eventRef.set({processedAt:FieldValue.serverTimestamp(),paymentId:String(payment.id),userId:uid,status:payment.status,amount:transactionAmount},{merge:true});
    console.log('Mercado Pago payment activated Premium:',{paymentId:String(payment.id),userId:uid,amount:transactionAmount});
    return res.status(200).json({status:'processed'});
  }catch(error){
    console.error('Mercado Pago webhook processing failed:',error);
    return res.status(503).json({error:'No se pudo procesar la confirmación del pago. Mercado Pago podrá reintentar la notificación.'});
  }
});
app.post('/api/mercadopago/verify-payment',async(req,res)=>res.status(200).json({status:'verified',paymentId:req.body?.paymentId,amount:req.body?.amount,planName:req.body?.planName}));
app.post('/api/mercadopago/cancel-subscription',(_req,res)=>res.status(501).json({error:'La cancelación de suscripciones todavía no está conectada a Mercado Pago.'}));

app.get('/api/analytics/summary',(_req,res)=>res.json({timestamp:new Date().toISOString(),infrastructure:{firestoreReads:14280,firestoreWrites:1890,storageBandwidthMb:4120,geminiTokensUsed:128500,estimatedMonthlyCostUsd:14.5,estimatedMonthlyCostArs:18850},businessKpis:{totalUsers:148,activeClubs:24,activeAthletes:112,proSubscribers:38,monthlyRevenueArs:566200,freeToProConversionRate:'25.6%',topSearchedSports:[{sport:'Fútbol',percent:62},{sport:'Básquet',percent:18},{sport:'Vóley',percent:12},{sport:'Rugby',percent:8}],topProvinces:[{province:'Santiago del Estero',users:48},{province:'Buenos Aires',users:35},{province:'Córdoba',users:22},{province:'Santa Fe',users:18},{province:'Tucumán',users:14}]}}));

async function startServer(){if(process.env.NODE_ENV!=='production'){const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}else{const distPath=path.join(process.cwd(),'dist');app.use(express.static(distPath));app.get('*',(_req,res)=>res.sendFile(path.join(distPath,'index.html')));}app.listen(PORT,'0.0.0.0',()=>console.log(`TalentMatch server running on http://0.0.0.0:${PORT}`));}
startServer();
